### ISSUE TITLE
No longer working with current version of proxy

### ISSUE THREAD

**Issue by dev-kino** [teralove/no-directional-skills#4]
This isn't working with proxy anymore. I wanted to grab this and add support for aerial scythe for warriors, but don't know enough about proxy to fix the rest of the problems with the module.

**Comment by teralove** [comment]
i'll take a look

**Comment by teralove** [comment]
try it now

**Comment by dev-kino** [comment]
Holy thank you so much, I can't tell you how many times I've fucked up aerial scythe, even a week after release. Great work.
