### ISSUE TITLE
Berserker Evasive Smash

### ISSUE THREAD

**Issue by ghost** [teralove/no-directional-skills#5]
You should comment out evasive smash in your config until you implement subskill only correction. Only the roll (subskill 0) for Evasive Smash is directional. The 2nd activation uses camera direction.

**Comment by teralove** [comment]
OK. Will do. What skill is evasive smash in config?

        1: true, // Punch
        40: true, // Quick Dash
        22: true, // Flying Kick

**Comment by teralove** [comment]
OK. It's done.
